# Generated by Django 3.1.2 on 2020-10-30 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='NotesPage',
        ),
    ]
